# Will log information about your current inventory size. Extra details in the
# server console
debug: false
# If the plugin is listening for events or not. Intended in case you need to
# disable the plugin without restarting the server
disabled: false

limit:
  # The maximum size that a players inventory is allowed to be
  inventory: 5223975
  # The maximum size of item that the player is allowed to pick up. If this is
  # to large, the player will be able to pick up an item, but will crash when
  # they open their inventory
  item: 731461
  # This is the maximum size of books that are allowed to be created, intended
  # to stop the creation of books for bookbans in survival servers
  book: 8000
