# Will log information about your current inventory size. Extra details in the
# server console
debug: false

limit:
  # The maximum size (in bytes) that a players inventory is allowed to be
  inventory: 33236
