name: BookBan
version: ${version}
author: TrickyPR
main: com.trickypr.bookban.BookBan
description: Stop bookbans before they crash players, with minimum gameplay impact
api-version: 1.13

commands:
  reloadbookban:
    description: Reload the bookban plugins config
    usage: /reloadbookban
    permission: bookban.reload
