name: BookBan
version: ${version}
author: TrickyPR
main: com.trickypr.bookban.BookBan
description: Stop bookbans before they crash players, with minimum gameplay impact
api-version: 1.13

commands:
  bookban:
    description: Allows for the configuration of bookbans
    usage: /bookban
    permission: bookban.reload
